databases:
  - name: Melody_Map_DB
    databaseName: melody_map_db
    user: Melody_Map
    region: singapore

services:
  - type: web
    name: Melody_Map
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Melody_Map_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

